-
insert name: insert("Timo")
insert surname: insert("Adameit")
insert full name: insert("Timo Adameit")
insert private mail: insert("@timo-adameit.de")
insert work mail: insert("adameit@informatik.uni-leipzig.de")
insert uni mail: insert("ta20qywy@studserv.uni-leipzig.de")
insert street: insert("Schützenhausstr. 6")
insert zip code: insert("04315")
insert city: insert("Leipzig")
insert address: insert("Schützenhausstr. 6\n04315 Leipzig")
insert organization: insert("Universität Leipzig")
